[package]
name = "rs-rcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "1.0.0-alpha.6"
clap = { version = "4.4.16", features = ["derive"] }
logos = "0.13.0"
